### ISSUE TITLE
Server icon (fixed)

### ISSUE THREAD

**Issue by suresttexas00** [benbaptist/minecraft-wrapper#80] opened 2015-01-21 05:55 UTC
Wrapper does not pass the server icon to the client server-list

**Comment by benbaptist** [comment] 2015-01-21 22:18
server-icon.png? That should be working. I'll have to test.

**Comment by suresttexas00** [comment] 2015-01-22 01:20
yes, mine stopped working after I transitioned to wrapper.

**Comment by benbaptist** [comment] 2015-01-31 04:16
I cannot reproduce your error. I see no issue and you have not provided any tracebacks, so I cannot help further. It's probably another Windows-only bug. 

You'll probably find Wrapper.py works a heck of a lot better on Linux, and I strongly recommend it if you can, even if it's just a virtual machine. I only say that since I've noticed you seem to encounter far more issues than anyone else since Windows can be a bit more picky. But, at the same time, I suppose it's good to fix these issues anyways :P

**Comment by suresttexas00** [comment] 2015-01-31 15:39
let me know were I will find the information, and I will get it.  I suspect maybe this might be fixed in your latest dev build... I'll test it out and let you know.  I don't see why the OS would affect this.

Yes, I think it is a good thing to find these "windows only" errors.  After all, you are marketing it for both Windows and Linux.. Which is a good thing, because yours is one of the only decent packages of this type available on windows... On Linux, there are far more choices.

**Comment by suresttexas00** [comment] 2015-01-31 16:06
I just retested this.  I tested it with various server jars from 1.8 to 1.8.2 pre-6, in case it was something Mojang broke.  I still get this;

![image](https://cloud.githubusercontent.com/assets/10001762/5988701/2d361ea6-a939-11e4-8bf6-6025503965f2.png)

**Comment by suresttexas00** [comment] 2015-01-31 16:08
The bukkit server is the only one displaying the Icon.  All my wrapper servers are showing the default icon.  How to i get you the information you are wanting?  The console is not producing errors because I am not eve logged onto the server.  Where would i look for a traceback if no error is being generated?

**Comment by saltstorm** [comment] 2015-02-02 08:24
Would like add that mine works fine on vanilla

**Comment by suresttexas00** [comment] 2015-02-02 16:20
I wonder if this is another case where because I am running directly from the src/ it is missing something that the zipped wrapper.py does contain...

**Comment by saltstorm** [comment] 2015-02-02 16:22
Maybe if you ask nicely the project owner will tell you how to compile it into one file :smile:

**Comment by suresttexas00** [comment] 2015-02-02 16:32
He has already shared how he does it.  I choose to use the entire folder.  It really makes no difference since the compiled wrapper.py is just a zipped up version of the /src folder.  At some point, if this project gets converted to Py3.x, the Py3 does not allow the same behavior.

instead of `python.exe wrapper.py`, I just use `pything.exe src/`

The problem is that his script was not uploading some of the files from his local /src folder to the online github folder.

**Comment by suresttexas00** [comment] 2015-02-02 16:34
after testing this, it is not a case of missing files or anything.  It still does not work running the zipped wrapper.py.

I tried switching to make proxy mode False and now it Does work, the the MOTD does not:

![image](https://cloud.githubusercontent.com/assets/10001762/6004256/718539ec-aacf-11e4-85a0-22c886f51062.png)

**Comment by suresttexas00** [comment] 2015-02-02 16:35
where in the script should i be looking for possible "windows" incompatibility?

**Comment by suresttexas00** [comment] 2015-02-02 16:38
By the way, Tom, I wanted to thank you ans OverJT Jonathan Toledo for your help in answering some of my programming questions and issues here.. THANKS! :)

Of course, thanks to Ben for creating this whole thing!

**Comment by saltstorm** [comment] 2015-02-02 17:00
I have proxy mode on and both the motd and server-icon work. It could be a windows issue, maybe windows is locking the file.

**Comment by suresttexas00** [comment] 2015-02-02 17:14
I tested it again... here are the results:
![image](https://cloud.githubusercontent.com/assets/10001762/6004953/b0c7d664-aad4-11e4-9f40-d06a1928f03b.png)
TIC Vanilla and Bukkit are my production servers. The vanilla runs wrapper.

The last two are the same server, my test server on this laptop, just accessed differently, one via direct to the 127.0.0.1 and he other through the proxy on port 25575.

**Comment by suresttexas00** [comment] 2015-02-02 17:16
It's confusing because whatever is going on here does not affect the bukkit server which is also in a proxy via BungeeCord.

**Comment by suresttexas00** [comment] 2015-02-06 17:13
So while looking at the namechange issue, I was poring over this code:'
```
				if os.path.exists("server-icon.png"):
					f = open("server-icon.png", "r")
					serverIcon = "data:image/png;base64," + f.read().encode("base64")
					f.close()
					MOTD["favicon"] = serverIcon
				self.send(0x00, "string", (json.dumps(MOTD),))
				self.state = 5
				return False
```
and I was thinking maybe there is something peculiar about my servericon.. so I thought maybe I would post it here so you can see if you can replicate the error with my icon..
![server-icon](https://cloud.githubusercontent.com/assets/10001762/6083808/83c66950-adf9-11e4-8fc8-664b7431f179.png)

**Comment by suresttexas00** [comment] 2015-02-06 17:14
ok.. so I need to get a link for the actual file :(

**Comment by suresttexas00** [comment] 2015-02-06 17:16
here it is:
https://www.dropbox.com/s/2eei45f0t105g6q/server-icon.png?dl=0

**Comment by benbaptist** [comment] 2015-02-20 04:42
I still cannot reproduce this bug myself. http://s.benbaptist.com/esyzP Is is still a problem?

**Comment by suresttexas00** [comment] 2015-02-20 05:31
yes, it still does it. :(

**Comment by suresttexas00** [comment] 2015-02-20 05:35
I bet saltstorm was right.. the server jar may be locking the file, preventing wrapper from accessing it.  Is is possible to have a second file that wrapper can use for the icon? ... It'w weird because my bungeecord servers don't experience this issue... ahhh.. because the bungeecord has its own folder and its own icon file!

**Comment by benbaptist** [comment] 2015-02-20 17:52
But my fix involved reading it before the server even started, hence
bypassing the whole lock thing.

**Comment by suresttexas00** [comment] 2015-02-20 18:36
Which fix? The "before" fix (how it was) or what you just sent out, build 92?

**Comment by benbaptist** [comment] 2015-02-20 21:20
yeah, the one I just sent out last night, 92 - although I realize that build was completely borked in terms of the MOTD thing.

**Comment by benbaptist** [comment] 2015-02-20 23:14
Build 93 should now be safe and ready to go.

**Comment by suresttexas00** [comment] 2015-02-21 19:22
Still no luck with latest build 94.

**Comment by suresttexas00** [comment] 2015-02-21 21:14
I placed code in proxy to log what steps were being executed and 
```
[15:43:40] [Wrapper.py/INFO] Server started
[15:43:40] [Wrapper.py/DEBUG] Does server icon exist?:
[15:43:40] [Wrapper.py/DEBUG] SERVER ICON EXISTS
[15:44:00] [Server thread/WARN]: Can't keep up! Did the system time change, or i
s the server overloaded? Running 2088ms behind, skipping 41 tick(s)
[15:44:07] [Wrapper.py/DEBUG] Looking for a FAVICON line 311
[15:44:07] [Wrapper.py/DEBUG] There is a FAVICON line 311
```
So I have no idea what gives.. I also have noticed that the available player slots shows the Minecraft jar number from server.properties (on mine 40), not the number in wrapper.properties (100 on mine)...

**Comment by benbaptist** [comment] 2015-02-21 22:32
Yeah, I removed the max-players from newer versions in favor of just using
server.properties which made more sense. This is incredibly weird. What
happens when you print self.proxy.serverIcon in the code that sends the
MOTD to the client? Does it print a massive data URL?

**Comment by suresttexas00** [comment] 2015-02-21 22:49
How would I print that..? Won't contain binary data or something from the Icon?  Would I just `self.log.debug((str0 self.proxy.serverIcon))` ?

Also, I kind of like the thought of using the wrapper number because I could hide the "real" number for various applications (like a server hub, for instance).  Also, can we have it (or an option to) not display the player names to client pings?

**Comment by benbaptist** [comment] 2015-02-22 17:40
No, the serverIcon variable is a data URL, so it is essentially the
server-icon.png turned into a hex string, in this format:
```data:image/PNG;base64,[hexified PNG file]```

And it would be better if you just print it, not using self.log.debug, as
that'll fill your log files up otherwise.

**Comment by suresttexas00** [comment] 2015-02-22 17:43
If I use "print", where does it end up going??

**Comment by suresttexas00** [comment] 2015-02-22 17:50
OK.. console...

Here's what it gives:
```
[12:48:43] [Wrapper.py/DEBUG] Looking for a FAVICON line 311
[12:48:43] [Wrapper.py/DEBUG] There is a FAVICON line 311
data:image/png;base64,iVBORwo=
```

**Comment by suresttexas00** [comment] 2015-02-22 17:52
Pinged it three times so you can see there is a CRLF here too:

```
[12:48:43] [Wrapper.py/DEBUG] Looking for a FAVICON line 311
[12:48:43] [Wrapper.py/DEBUG] There is a FAVICON line 311
data:image/png;base64,iVBORwo=

[12:50:23] [Wrapper.py/DEBUG] Looking for a FAVICON line 311
[12:50:23] [Wrapper.py/DEBUG] There is a FAVICON line 311
data:image/png;base64,iVBORwo=

[12:50:38] [Wrapper.py/DEBUG] Looking for a FAVICON line 311
[12:50:38] [Wrapper.py/DEBUG] There is a FAVICON line 311
data:image/png;base64,iVBORwo=
```

**Comment by benbaptist** [comment] 2015-02-22 18:55
Wait, is that all it prints? Or did you just cut off the rest?

**Comment by suresttexas00** [comment] 2015-02-22 19:00
That's it!  I have had problems reading files in python with windows where it puts extra LF or CR at the end of each line while reading.. suspect that may be happening here.. or something related to it....

**Comment by suresttexas00** [comment] 2015-02-22 19:00
I did not cut anything off...

**Comment by benbaptist** [comment] 2015-02-22 19:14
*Sigh* Windows Windows Windows.... what am I going to do with you?

Hmm, as another test, what does os.path.getfilesize("server-icon.png") say? Does it properly return the filesize in bytes?

**Comment by suresttexas00** [comment] 2015-02-22 19:29
```
[14:27:59] [Wrapper.py/DEBUG] Does server icon exist?:
[14:27:59] [Wrapper.py/DEBUG] SERVER ICON EXISTS
[14:28:09] [Wrapper.py/DEBUG] Looking for a FAVICON line 311
[14:28:09] [Wrapper.py/DEBUG] There is a FAVICON line 311
Error in the Client->Server method:
Traceback (most recent call last):
  File "src\proxy.py", line 515, in handle
    if self.parse(id) and self.server:
  File "src\proxy.py", line 316, in parse
    print(os.path.getfilesize("server-icon.png"))
AttributeError: 'module' object has no attribute 'getfilesize'

[14:28:10] [Wrapper.py/INFO] SurestTexas logged in with older name previously, f
alling back to SurestTexas` << Hmmmmm.......`
[14:28:10] [Wrapper.py/INFO] SurestTexas logged in (UUID: 54880482-2b03-47e5-a26
8-8290fd1e0b46 | IP: 184.17.171.192)
```

**Comment by suresttexas00** [comment] 2015-02-22 19:30
the falling back name thing again.. what line again was that in where the not X != Y was..?

**Comment by suresttexas00** [comment] 2015-02-22 19:32
wait never mind.. these guys DID do name changes

**Comment by benbaptist** [comment] 2015-02-22 21:02
try .getsize insead

**Comment by suresttexas00** [comment] 2015-02-22 21:34
returns 8482

**Comment by suresttexas00** [comment] 2015-02-22 22:34
unrelated - 
What is with the need for the extra[] json text to be nested?  if I want something like:

Bluetext redtext  Bluetext redtext Bluetext redtext Bluetext redtext Bluetext redtext Bluetext redtext Bluetext redtext Bluetext redtext Bluetext redtext Bluetext redtext...

I cant just add a Bluetext or a redtext.. I gotta keep nesting it deeper and deeper in the last extra text.. who invented this system!!!???

**Comment by benbaptist** [comment] 2015-02-23 07:13
I INVENTED THAT SYSTEM. just kidding :P

extra is a list. You're not supposed to go deeper, but rather add more
entries to it. E.g.

Extra:[{text:red,color:red}, {text:blue,color:blue}] and so on

Is 8000 bytes around the actual size of the file? (About 8KB?)

**Comment by suresttexas00** [comment] 2015-02-23 19:49
The 8482 is actually the EXACT file size, per the file properties.

Did not know that about extra... so why is the extra even needed.. why cant you just add items directly to the Json without and "extra" piece?

**Comment by benbaptist** [comment] 2015-02-23 22:31
We're talking about tellraw-esque stuff in Minecraft, right?

**Comment by benbaptist** [comment] 2015-02-23 22:34
You can't just add more stuff to the same dictionary, as it overrides each other. e.g.

```{text:red,color:red,text:blue,color:blue}```

All you'll get is a message with 'blue' with the color blue. You just overrode the properties containing the original text. As a result, to add more text with different properties, you'll use extra. 

```{text:red,color:red,extra:[{text:blue,color:blue}]}```

That's just the way Mojang had to do it due to the nature of JSON. I have no clue if we're talking about the same thing though. I assumed you already knew about the "Extra" tag since you said extra[] earlier.

**Comment by suresttexas00** [comment] 2015-03-03 13:06
just noticed this from my gameplay window:
```
java.lang.NullPointerException
	at azl.c(SourceFile:216) [1.8.3.jar:?]
	at azl.a(SourceFile:145) [1.8.3.jar:?]
	at awe.a(SourceFile:25) [1.8.3.jar:?]
	at awj.b(SourceFile:412) [1.8.3.jar:?]
	at awj.a(SourceFile:211) [1.8.3.jar:?]
	at azi.a(SourceFile:291) [1.8.3.jar:?]
	at bfl.a(SourceFile:1039) [1.8.3.jar:?]
	at avf.av(SourceFile:914) [1.8.3.jar:?]
	at avf.a(SourceFile:325) [1.8.3.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [1.8.3.jar:?]
[07:45:17] [Client thread/INFO]: Connecting to theimaginecraft.com., 25566
[07:45:18] [Client thread/INFO]: [CHAT] Welcome back, SurestTexas00.  Some /help commands are clickable!
[07:45:26] [Client thread/ERROR]: Invalid icon for server TIC Vanilla 66 (vanilla.theimaginecraft.com)
java.lang.NullPointerException
	at azl.c(SourceFile:216) [1.8.3.jar:?]
	at azl.a(SourceFile:145) [1.8.3.jar:?]
	at awe.a(SourceFile:25) [1.8.3.jar:?]
	at awj.b(SourceFile:412) [1.8.3.jar:?]
	at awj.a(SourceFile:211) [1.8.3.jar:?]
	at azi.a(SourceFile:291) [1.8.3.jar:?]
	at bfl.a(SourceFile:1039) [1.8.3.jar:?]
	at avf.av(SourceFile:914) [1.8.3.jar:?]
	at avf.a(SourceFile:325) [1.8.3.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [1.8.3.jar:?]
```

**Comment by benbaptist** [comment] 2015-06-23 22:42
Is this still broken? If not, I'd like to close it, but if it is, I need to figure it out still. Did we ever figure out the issue and/or was it fixed?

**Comment by suresttexas00** [comment] 2015-06-23 23:45
It was never fixed.  I'll verify if build 101 solved it in some way...

**Comment by suresttexas00** [comment] 2015-06-28 04:54
Still broken.  Has to be the wrapper.  I turned off wrapper and ran the server directly and the icon worked.. once I went to proxy mode.. no icon... So I know it is not a bad icon file or something.

**Comment by benbaptist** [comment] 2015-06-28 21:22
I know it works, because I've used your exact icon as well with Wrapper. I can 100% guarantee that this is some ridiculous Windows issue, probably because of the file being in use. If I pre-load the icon, though, then you'd have to reboot the whole wrapper just to change the icon. It's utter crap how Windows handles files. It really is. It's the reason your log rotation is broken. I'm almost 100% positive of it. 'Tis why I never, *ever* use Windows for anything - especially server hosting. It's gosh awful for it, and this is proof. The amount of patches I've made to Wrapper just to get it half-way functional on Windows is pretty unbelievable. It is true that I developed this for Linux, but it runs on other non-Windows non-Linux platforms flawlessly without any modifications. OS X, OpenBSD, Solaris, etc.

I Billy Mays guarantee that if you switch to a Linux VM or something, almost all of these issues will go away. :P

**Comment by benbaptist** [comment] 2015-06-28 22:53
For now, I'll just make it load upon loading server.properties (done prior to starting the server). If this does not fix this issue, I don't know what will.

**Comment by suresttexas00** [comment] 2015-06-28 23:09
I don't know, i'll keep looking into it.

**Comment by benbaptist** [comment] 2015-06-29 02:44
Alright, RC2 is out. Try it out. :D

**Comment by suresttexas00** [comment] 2015-07-04 19:32
Well, you can just forget about making it load before the server start and do it the old way...  I found the problem. Whether it's "windows" or not, I don't know.. but in this code in `def host` of proxy.py:
```
		if os.path.exists("server-icon.png"):
			f = open("server-icon.png", "r")
			self.serverIcon = "data:image/png;base64," + f.read().encode("base64")
			f.close()
```

Should be `f = open("server-icon.png", "rb")`

Viola.. icon works!

**Closed** 2015-07-07 23:19 UTC
Labels: bug, proxy mode, windows

**Comment by suresttexas00** [comment] 2015-07-07 23:55
Yea!  A build! :D
