### ISSUE TITLE
IRC connection

### ISSUE THREAD

**Issue by AnanyaIG** [benbaptist/minecraft-wrapper#261] opened 2016-01-05 06:29 UTC
So this is my first time running this wrapper. And I'm getting this error, according to the traceback log.

[2016-01-05 06:02:04] [Wrapper.py/INFO] Disconnected from IRC
[2016-01-05 06:02:09] [Wrapper.py/INFO] Connecting to IRC...
[2016-01-05 06:03:12] [Wrapper.py/ERROR] Traceback (most recent call last):
[2016-01-05 06:03:12] [Wrapper.py/ERROR]   File "Wrapper.py/irc.py", line 39, in init
[2016-01-05 06:03:12] [Wrapper.py/ERROR]     self.connect()
[2016-01-05 06:03:12] [Wrapper.py/ERROR]   File "Wrapper.py/irc.py", line 53, in connect
[2016-01-05 06:03:12] [Wrapper.py/ERROR]     self.socket.connect((self.address, self.port))
[2016-01-05 06:03:12] [Wrapper.py/ERROR]   File "/usr/lib/python2.7/socket.py", line 224, in meth
[2016-01-05 06:03:12] [Wrapper.py/ERROR]     return getattr(self._sock,name)(*args)
[2016-01-05 06:03:12] [Wrapper.py/ERROR] error: [Errno 110] Connection timed out
[2016-01-05 06:03:12] [Wrapper.py/ERROR]
[2016-01-05 06:03:12] [Wrapper.py/INFO] Disconnected from IRC

Any ideas on what's going wrong?

**Comment by JasonBristol** [comment] 2016-01-05 06:41
What does your `wrapper.properties` file look like?

**Comment by AnanyaIG** [comment] 2016-01-05 06:52
It looks something like this.

[General]
server-name = NWCraft Server
command = java -Xmx1200M -jar minecraft_server.1.8.9.jar nogui
auto-restart = True
auto-update-wrapper = False
auto-update-dev-builds = False
pre-1.7-mode = False
timed-reboot = False
timed-reboot-seconds = 86400
timed-reboot-warning-minutes = 5
debug = False
shell-scripts = False
auto-update-dev-build = False

[Backups]
enabled = True
backup-folders = ['server.properties', 'world']
backup-interval = 3600
backup-notification = True
backup-location = backup-directory
backup-compression = False
backups-keep = 10

[IRC]
irc-enabled = False
server = irc.server.com
port = 6667
nick = Botnick_echo
channels = ['#IRCChannel']
command-character = .
show-channel-server = True
autorun-irc-commands = ['NS ID Password', 'MODE Botnick_echo +RBp', 'PRIVMSG Ananya: I have Connected sucessfully']
obstruct-nicknames = False
control-from-irc = False
control-irc-pass = passcode

[Proxy]
proxy-enabled = False
proxy-port = 25565
proxy-bind = 0.0.0.0
server-port = 25564
online-mode = True
max-players = 1024

[Web]
web-enabled = False
web-bind = 0.0.0.0
web-port = 8070
web-password = password
web-allow-file-management = True
public-stats = True

That's it. Also, it's all too long and takes us to scroll. How to add all that as <code>?

**Comment by suresttexas00** [comment] 2016-01-05 13:52
You can start with enabling IRC (irc-enabled= True)

**Comment by AnanyaIG** [comment] 2016-01-05 14:56
Lol, I've had it enabled. Don't you think that's how I got those errors? I then disabled it in order to get rid of the errors in the log file.

**Comment by suresttexas00** [comment] 2016-01-06 00:50
I did not read the original message; it just caught my eye that you had it set to False.  So why post a configuration or setting that is not what produced the error?  "Garbage in => Garbage out."   As far as anything else, I don't use IRC... sorry.

**Comment by AnanyaIG** [comment] 2016-01-07 17:03
Sorry for the late reply. And I posted it cuz JasonBristol up there asked for it. And it is what caused it, when it was set true and thats how the errors came up, dont you think? And I think you still haven't read all of it properly. Either that or its english being the medium of miscommunication. Anyways, still need help. Also, edited the post above.

**Comment by benbaptist** [comment] 2016-01-08 01:02
This just means that it simply wasn't able to connect to the IRC server - in this case, irc.server.com (is that even valid?). It might also be a result of the IRCd having some weird configuration or something else.

**Comment by AnanyaIG** [comment] 2016-01-08 16:14
Oh okay. Thanks for the comment. I'm pretty  sure that the server (it's valid, I replaced the original domain to this) I'm trying to connect to is valid. I've got my BNC and bots connected there. However I'm not sure abour the IRCd as i dont own it. Either way, its unreal ircd if that helps.

**Comment by suresttexas00** [comment] 2016-01-08 16:16
I read it properly... my point was that you did not post the file "as is"; you posted it after changing something (disabling it)..  sometimes, simple things like that cause errors; I was simply trying to be helpful. I simply reacted to the first thing I saw; that it was set to False in the config...  __Ok already, I'll take the hit for not reading (initially) the original error text to see that the IRC would have to have been enabled..__    No need for you to be snarky...

**Comment by AnanyaIG** [comment] 2016-01-08 16:19
Okay, no worries. Moving on, I will try connecting to another IRC server and I'll let you guys know about it. And if it doesn't work, then I'll create a test ircd and try it on that.

**Comment by AnanyaIG** [comment] 2016-01-08 18:03
Okay, so I've tried connecting it to different servers but it doesn't seem to work. Same error message. @benbaptist Did you guys have any such problems with IRC in the past, and while you might've been testing, you would've connected it to an IRC network, right? So could we maybe compare things which are different between this and that? Maybe the configurations or the properties file? Cuz I've tried it all, and nothing seems to solve it. Please help.

**Comment by JasonBristol** [comment] 2016-01-08 21:13
Is port 6667 open on your system/firewall?

**Comment by AnanyaIG** [comment] 2016-01-09 06:07
I suppose it is. But just to make sure, I added those rules to iptables. Still no luck.

**Comment by JasonBristol** [comment] 2016-01-09 06:32
Just from an initial glance and looking at the time stamps it is possible that your network configuration isn't allowing traffic in or out. If you have already opened 6667 (UDP & TCP) then I would next confirm that you are forwarding 6667 to your server from your router.

**Comment by AnanyaIG** [comment] 2016-01-12 09:20
Sorry for replying late, was stuck on the path of life. :P 
Anyways, still no luck. I'm positive the rules are working. Talking to the hosts now. See if the problem's on their end. I'll let you guys know what's happening. Thanks for your time guys.

**Comment by benbaptist** [comment] 2016-01-20 16:30
Ohai! Just checking back, did you have any luck getting it to connect?

**Comment by AnanyaIG** [comment] 2016-01-28 15:27
Nah, I had to give up on connecting to IRC.

**Comment by suresttexas00** [comment] 2016-01-28 20:32
I'm sorry to hear that... Don't take this the wrong way because I know it is a basic thing...  I know you configured your computer's IPtables, and I know JasonBristol already mentioned this but it really sounds like your router (wireless, I assume?) is not port forwarding to your computer.  Again, I don't know what your hardware setup it like, but on mine, I did not have to mess with IPtables for any networking as long as the port forwarding on my router is configured properly and the server/client is properly bound to the port and running.

I guess I should try to set up IRC sometime just as a test to make sure it works; so I can be more informed and helpful.

**Comment by suresttexas00** [comment] 2016-05-24 23:23
I'm going to reference this over to my fork for looking into at some point.

**Comment by suresttexas00** [comment] 2016-10-30 14:48
I still don't know how this code would fail to at least produce a connection:
```
    def connect(self):
        self.nickname = self.originalNickname[0:]
        self.socket = socket.socket()
        self.socket.connect((self.address, self.port))
        self.socket.setblocking(120)

        self.auth()

    def auth(self):
        if self.config["IRC"]["password"]:
            self.send("PASS %s" % self.config["IRC"]["password"])
        self.send("NICK %s" % self.nickname)
        self.send("USER %s 0 * :%s" % (self.nickname, self.nickname))
```
The only possibilities seem to be:
1) Network problem/configuration
2) Possibly an encoding difference between the client and server??

Since the original error is a "Connection timed out", it is not, strictly speaking, a wrapper error.  We just don't really seem to have anything to go on unless one of us can produce the error on our own.

I also note by the line number that you are using the master branch, which (as far as I know) has never experienced any IRC issues, as it is largely un-modified and it's sole authorship is Benbaptist (so I know it was not broken by our refactoring of the development branch)

Since one possibility is character encoding, perhaps you could tell us about your system?  operating system and your local character encoding?  Also, what software you are using to (successfully) connect to IRC?

**Comment by suresttexas00** [comment] 2016-12-04 17:50
OP unable to reproduce due to changes in server/host configurations.  Closing without resolution.

**Comment by suresttexas00** [comment] 2018-01-01 19:03
I was able to successfully connect using these options on Build 252 (pushing shortly).  Please note, IRC will currently malfunction on Python 3 because differences in PY2-3 unicode/string/bytecode things.
```
  "IRC": {
    "autorun-irc-commands": [
      "COMMAND 1",
      "COMMAND 2"
    ],
    "channels": [
      "#suresttestchan"
    ],
    "command-character": ".",
    "control-from-irc": false,
    "control-irc-pass": "gAAAAABaR_4G6eo4d1_UeOt9RGXwdtbWTaTgNM_ckG4b6TCK9Dmh06YQAPnup1F0gxyAozjaalm74stgmRnPJgJ2xuhpvw==",
    "control-irc-pass-plaintext": false,
    "irc-enabled": true,
    "nick": "Surest",
    "obstruct-nicknames": false,
    "password": "gAAAAABaSm_dm4nyOXvKPJEtwim6FMoniiXB6GKfkMyVDJF_kcMAH2iyehX4vBFHxMfJJie-CZnTqN3LhA919MVv2B6AWYg==",
    "password-plaintext": false,
    "port": 6667,
    "server": "irc.freenode.net",
    "show-channel-server": true,
    "show-irc-join-part": true
  },
```

```
* surest sets mode +i on surest
* Now talking on #suresttestchan
* leguin.freenode.net sets mode +n on #suresttestchan
* leguin.freenode.net sets mode +s on #suresttestchan
* Surest_ (~Surest@1375155-v260***********************c.net) has joined
<Surest_> Server starting...
<Surest_> [SurestTexas00 connected]
<Surest_> SurestTexas00 tried to swim in lava
<Surest_> <SurestTexas00> hello there
<surest> hello there
<Surest_> <SurestTexas00> its dark out
<Surest_> [SurestTexas00 disconnected]
```

**Closed** 2018-01-01 19:04 UTC
Labels: high priority, needs investigation, OP reply needed
